// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYPce9o5_2FEWDeY4--glXCHdQX5s3_Kg',
    appId: '1:733280798337:web:401818a932853964292f80',
    messagingSenderId: '733280798337',
    projectId: 'event-management-app-d7b56',
    authDomain: 'event-management-app-d7b56.firebaseapp.com',
    storageBucket: 'event-management-app-d7b56.appspot.com',
    measurementId: 'G-T39LQ9XJGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB99Ls2OV_g4lUMroQcoOsTRffkHOlmSR0',
    appId: '1:733280798337:android:46b2db72437808d6292f80',
    messagingSenderId: '733280798337',
    projectId: 'event-management-app-d7b56',
    storageBucket: 'event-management-app-d7b56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI1pSndIF4cUeZqQF6AljXoIaafrTjiAU',
    appId: '1:733280798337:ios:368827fb3d129812292f80',
    messagingSenderId: '733280798337',
    projectId: 'event-management-app-d7b56',
    storageBucket: 'event-management-app-d7b56.appspot.com',
    iosClientId: '733280798337-q3rgvlvm01vpktucbde1tf4dqnnchpo8.apps.googleusercontent.com',
    iosBundleId: 'com.helloworld.eventManagement',
  );
}
